### ISSUE TITLE
Porting to Godot - a few beginner's questions

### ISSUE THREAD

**Issue by 7wells** [unknown-horizons/godot-port#62]
Hello,

I am still very unexperienced with programming, GitHub etc., but willing to learn. Most of you may know that there is a forum for porting Unknown Hirozons to Godot at FreeGameDev. Since I do my first steps with Godot, I came across a few hurdles, I asked questions about. Julius over at FreeGameDev suggested that I oppen an issue here with the link to that thread of mine, so maybe some more interested people could have a look, give some hints etc. Thank you so much for your patience with me.

Here is the link to the forum thread:
https://forum.freegamedev.net/viewtopic.php?f=100&t=14356

**Comment by aaronfranke** [comment]
GitHub issues are not a good place to ask questions, this is a place to report bugs. You should consider joining the Discord server: https://discord.gg/rXuRGzw However, to answer your questions:

> Which Godot version shall I use for Unknown Horizons? (well, actually for first playing around a bit with Godot) The latest 3.2.2?

Yes, 3.2.2.

> Shall I use the Standard version or the Mono version (C# support)?

This project does not use C#, so both versions will open the project just fine. If you want to run C# projects later, download the Mono version of Godot (and install Mono itself too!), otherwise just download the standard version.

> Godot 32 or 64bit?

Always 64-bit.

> I understand that the Godot executable should be in one of these locations. Are there any further steps to do, e.g. setting some environment variables?

Well, those are some locations the build script looks in, but you can put Godot anywhere you want, and also, the built script isn't necessary to build the game, it's just to assist with exporting for all platforms at once (so you don't need it). No extra environment variables are necessary (the script does expect you have standard ones such as `$HOME`).

> In the terminal, I see this, and the build process fails after a while:

You need to open the project once in the Godot editor to generate the necessary files before the build script would work (but again, you probably don't need the build script).

> No export templates were found in the expected path:

Export templates can be installed from inside the Godot editor.

**Comment by 7wells** [comment]
Thank you so much! I have joined Discord and start reading first. 😉

If you agree, you can close my comment here.

**Comment by poVoq** [comment]
As request here: https://forum.freegamedev.net/viewtopic.php?f=100&t=16847
Please quickly confirm identity @LinuxDonald

**Comment by LinuxDonald** [comment]
@poVoq yes :)
